plugins {
    id 'java'
}

group = 'com.flyaway.furnaceupgrade'
version = '1.3.0'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

repositories {
    mavenCentral()
    maven {
        name = "papermc"
        url = "https://repo.papermc.io/repository/maven-public/"
    }
    maven { url = 'https://repo.nightexpressdev.com/releases'}
}

dependencies {
    compileOnly 'io.papermc.paper:paper-api:26.3.build.159-beta'
    compileOnly 'su.nightexpress.nightcore:main:2.16.4'
    compileOnly 'su.nightexpress.excellenteconomy:ExcellentEconomy:2.8.0'
}

tasks.jar {
    archiveBaseName.set("FurnaceUpgrade")
}

tasks.processResources {
    filesMatching("plugin.yml") {
        expand(
                version: project.version,
                name: project.name,
                group: project.group
        )
    }
}
